### ISSUE TITLE
Admin Login URL?

### ISSUE THREAD

**Issue by suppqt** [Grisu118/image-shop#11]
Hey Grisu,

erstmal dickes Danke für deine Arbeit hier.
War etwas wackelig, dass ganze zum laufen zu bekommen. Mit Custom PHP Handler hats dann allerdings geklappt.

Soweit so gut, allerdings finde ich keine Möglichkeit mich einzuloggen ins backend?
Wollte das gute Ding zum üben etwas auseinandernehmen und erweitern.

![image](https://user-images.githubusercontent.com/3234897/208468453-47ad8bf7-2ef7-408a-adc9-1a278fb01c1a.png)

Danke !

**Comment by suppqt** [comment]
PS: Apache2 config habe ich auf ..image-shop/public/ gesetzt

**Comment by Grisu118** [comment]
Hallo e0xify,

Auf das Admin Backend kommst du mit /a,
siehe https://github.com/Lightspots/image-shop/blob/19765e0e44fe9d2e1a86f01c3b636be90a037a3a/app/Http/routes.php#L16

**Comment by suppqt** [comment]
> age-shop/app/Http/routes.php

Perfekt ! bin noch nicht so fit, danke dir !
