### ISSUE TITLE
 public function mail()

### ISSUE THREAD

**Issue by suppqt** [Grisu118/image-shop#12]
Moin nochmal,

im publiccontroller gibts die mailfunktion die laut kommentar per cronjob getriggert wird.
Wie wird das denn umgesetzt ?

Ist das DIng schon komplett implementiert?
Ich bekomm leider keinerlei fehlermeldung, mail kommt auch nicht an.
Kann man das irgendwie sauber debuggen?

Danke

**Comment by Grisu118** [comment]
Nein, das ist nicht automatisch umgesetzt. Ich habe bei mir aktuell ein systemd timer laufen, der alle 5 min die api aufruft

trigger_mail_send.service:
```
[Unit]
Description=Executes the mail sending hook of <Your App>

[Service]
Type=oneshot
User=root
ExecStart=/usr/bin/curl <your url>/api/mail
```

trigger_mail_send.timer:
```
[Unit]
Description=Executes the mail sending hook of <your App> every 5 minutes

[Timer]
# every 5 minutes
OnCalendar=*:0/5

[Install]
WantedBy=multi-user.target
```

**Comment by suppqt** [comment]
perfekt danke
funktioniert wunderbar, baue ich mir dann einfach als cron.
